Initial game setup
FACapplicants/summer2024 pull request #131
Opened 2024-07-01 13:52 UTC by gurtatiLND

- made the initial setup of the game(HTML, CSS and JS files, and assets folder);
- added some logic and initial page view;

Please review my PR and leave feedback.
Thank you.

2024-07-02 09:51 UTC, lopezelpesado requested changes

2024-07-02 09:51 UTC, lopezelpesado commented on README.md
Please don't delete the README 😭

2024-07-02 14:36 UTC, lopezelpesado commented on README.md
I think I know what's happened here. The easiest thing would probably be to save these files somewhere, start fresh with a new branch off main (make sure your main branch is up to date), add your files and make a new pull request 👍

2024-07-03 08:54 UTC, gurtatiLND commented on README.md
OK, almost done

2024-07-09 10:23 UTC, lopezelpesado commented
Looks like you managed to get your code in with #138! Nice one and thank you for not deleting the `README.md`!

2024-07-09 10:23 UTC, closed without merging